version: "3.8"
# https://docs.docker.com/compose/compose-file/compose-file-v3/
services:
  caddy:
    image: caddy:latest
    # https://hub.docker.com/_/caddy
    volumes:
      - static:/var/www/healthchecks/static
      - caddy_data:/data
    networks:
      - healthchecks
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: healthchecks_caddyfile
        target: /etc/caddy/Caddyfile
    environment:
      # https://caddyserver.com/docs/automatic-https#overview
      - DOMAIN=healthchecks.yourdomain.test

  healthchecks:
    image: zeigren/healthchecks:latest # ghcr.io/zeigren/healthchecks_docker:latest
    # https://hub.docker.com/r/zeigren/healthchecks
    networks:
      - healthchecks
    volumes:
      - static:/usr/src/static
      - db:/usr/src/app/db
    environment:
      - REGISTRATION_OPEN=True
      - SITE_ROOT=https://healthchecks.yourdomain.test
      # - MATRIX_ACCESS_TOKEN=DOCKER-SECRET->BOT_MATRIX_ACCESS_TOKEN
    # secrets:
    #   - BOT_MATRIX_ACCESS_TOKEN

networks:
  healthchecks:

volumes:
  static:
  caddy_data:
  db:

configs:
  healthchecks_caddyfile:
    external: true

#secrets:
# BOT_MATRIX_ACCESS_TOKEN:
#   external: true
