version: '3.7'
services:
  nginx:
    image: nginx:alpine
    networks:
      - healthchecks
    volumes:
      - static:/var/www/healthchecks/static
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: healthchecks_vhost
        target: /etc/nginx/conf.d/default.conf
    secrets:
      - source: yourdomain.test.crt
        target: /etc/nginx/certs/yourdomain.test.crt
      - source: yourdomain.test.key
        target: /etc/nginx/certs/yourdomain.test.key

  healthchecks:
    image: zeigren/healthchecks:latest
    networks:
      - healthchecks
    volumes:
      - static:/usr/src/static
      - db:/usr/src/app/db
    environment:
      - REGISTRATION_OPEN=True
      - SITE_ROOT=https://healthcheck.yourdomain.test
      # - MATRIX_ACCESS_TOKEN=DOCKER-SECRET->BOT_MATRIX_ACCESS_TOKEN
    # secrets:
    #   - BOT_MATRIX_ACCESS_TOKEN

networks:
  healthchecks:

volumes:
  static:
  db:

configs:
  healthchecks_vhost:
    external: true

secrets:
  yourdomain.test.crt:
    external: true
  yourdomain.test.key:
    external: true
#   BOT_MATRIX_ACCESS_TOKEN:
#     external: true
