version: "3.8"
# https://docs.docker.com/compose/compose-file/compose-file-v3/
services:
  nginx:
    image: nginx:alpine
    # https://hub.docker.com/_/nginx
    networks:
      - healthchecks
    volumes:
      - static:/var/www/healthchecks/static
    ports:
      # CHANGE TO "80:80" IF USING NGINX FOR SSL TERMINATION
      - "9080:80"
      # UNCOMMENT IF USING NGINX FOR SSL TERMINATION
      # - "443:443"
    configs:
      - source: healthchecks_vhost
        target: /etc/nginx/conf.d/default.conf
    secrets:
    # UNCOMMENT IF USING NGINX FOR SSL TERMINATION
    # secrets:
    #   - source: yourdomain.test.crt
    #     target: /etc/nginx/certs/yourdomain.test.crt
    #   - source: yourdomain.test.key
    #     target: /etc/nginx/certs/yourdomain.test.key

  healthchecks:
    image: zeigren/healthchecks:latest
    # https://hub.docker.com/r/zeigren/healthchecks
    networks:
      - healthchecks
    volumes:
      - static:/usr/src/static
      - db:/usr/src/app/db
    environment:
      - REGISTRATION_OPEN=True
      - SITE_ROOT=https://healthchecks.yourdomain.test
      # - MATRIX_ACCESS_TOKEN=DOCKER-SECRET->BOT_MATRIX_ACCESS_TOKEN
    # secrets:
    #   - BOT_MATRIX_ACCESS_TOKEN

networks:
  healthchecks:

volumes:
  static:
  db:

configs:
  healthchecks_vhost:
    external: true

secrets:
# UNCOMMENT IF USING NGINX FOR SSL TERMINATION
# yourdomain.test.crt:
#   external: true
# yourdomain.test.key:
#   external: true
#   BOT_MATRIX_ACCESS_TOKEN:
#     external: true
