version: "3.7"
services:
  nginx:
    image: nginx:alpine
    networks:
      - healthchecks
      - traefik
    volumes:
      - static:/var/www/healthchecks/static
    configs:
      - source: healthchecks_vhost
        target: /etc/nginx/conf.d/default.conf
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.healthcheck.entrypoints=websecure"
        - "traefik.http.routers.healthcheck.rule=Host(`healthcheck.yourdomain.test`)" # Domain name
        - "traefik.http.routers.healthcheck.tls=true"
        - "traefik.http.routers.healthcheck.tls.certresolver=myresolver"
        - "traefik.http.services.healthcheck.loadbalancer.server.port=80" # Port traefik needs to route traffic to
        # Security Headers https://doc.traefik.io/traefik/middlewares/headers/
        - "traefik.http.middlewares.healthcheck_headers.headers.sslredirect=true"
        - "traefik.http.middlewares.healthcheck_headers.headers.sslforcehost=true"
        - "traefik.http.middlewares.healthcheck_headers.headers.sslhost=healthcheck.yourdomain.test" # Domain name
        - "traefik.http.middlewares.healthcheck_headers.headers.forcestsheader=true"
        - "traefik.http.middlewares.healthcheck_headers.headers.stsseconds=315360000"
        - "traefik.http.middlewares.healthcheck_headers.headers.browserxssfilter=true"
        - "traefik.http.middlewares.healthcheck_headers.headers.contenttypenosniff=true"
        - "traefik.http.middlewares.healthcheck_headers.headers.customFrameOptionsValue=SAMEORIGIN"
        # If healthcheck is down drop connections until it's back up https://doc.traefik.io/traefik/middlewares/circuitbreaker/
        - "traefik.http.middlewares.healthcheck_circuitbreaker.circuitbreaker.expression=NetworkErrorRatio() > 0.30"
        # Enable Middlewares
        - "traefik.http.routers.healthcheck.middlewares=healthcheck_headers@docker,healthcheck_circuitbreaker@docker"

  healthchecks:
    image: zeigren/healthchecks:latest
    networks:
      - healthchecks
    volumes:
      - static:/usr/src/static
      - db:/usr/src/app/db
    environment:
      - REGISTRATION_OPEN=True
      - SITE_ROOT=https://healthcheck.yourdomain.test
      # - MATRIX_ACCESS_TOKEN=DOCKER-SECRET->BOT_MATRIX_ACCESS_TOKEN
    # secrets:
    #   - BOT_MATRIX_ACCESS_TOKEN

networks:
  healthchecks:
  traefik:
    external: true

volumes:
  static:
  db:

configs:
  healthchecks_vhost:
    external: true

# secrets:
#   BOT_MATRIX_ACCESS_TOKEN:
#     external: true
