version: "3.7"
# https://docs.docker.com/compose/compose-file/compose-file-v3/
services:
  nginx:
    image: nginx:alpine
    # https://hub.docker.com/_/nginx
    networks:
      - healthchecks
    volumes:
      - static:/var/www/healthchecks/static
      - ./config/healthchecks_vhost.conf:/etc/nginx/conf.d/default.conf
      # UNCOMMENT IF USING NGINX FOR SSL TERMINATION
      # - ./config/yourdomain.test.crt:/etc/nginx/certs/yourdomain.test.crt
      # - ./config/yourdomain.test.key:/etc/nginx/certs/yourdomain.test.key
    ports:
      # CHANGE TO "80:80" IF USING NGINX FOR SSL TERMINATION
      - "9080:80"
      # UNCOMMENT IF USING NGINX FOR SSL TERMINATION
      # - "443:443"

  healthchecks:
    image: zeigren/healthchecks:latest
    # https://hub.docker.com/r/zeigren/healthchecks
    networks:
      - healthchecks
    volumes:
      - static:/usr/src/static
      - db:/usr/src/app/db
    environment:
      - REGISTRATION_OPEN=True
      - SITE_ROOT=http://localhost:9080

networks:
  healthchecks:

volumes:
  static:
  db:
