version: "3.7"
# https://docs.docker.com/compose/compose-file/compose-file-v3/
services:
  caddy:
    image: caddy:latest
    # https://hub.docker.com/_/caddy
    volumes:
      - static:/var/www/healthchecks/static
      - caddy_data:/data
      - ./healthchecks_caddyfile:/etc/caddy/Caddyfile
    networks:
      - healthchecks
    ports:
      # CHANGE TO "80:80" IF USING CADDY FOR HTTPS
      - "9080:80"
      # UNCOMMENT IF USING CADDY FOR HTTPS
      # - "443:443"
    environment:
      # https://caddyserver.com/docs/automatic-https#overview
      - DOMAIN=:80

  healthchecks:
    image: zeigren/healthchecks:latest # ghcr.io/zeigren/healthchecks_docker:latest
    # https://hub.docker.com/r/zeigren/healthchecks
    networks:
      - healthchecks
    volumes:
      - static:/usr/src/static
      - db:/usr/src/app/db
    environment:
      - REGISTRATION_OPEN=True
      - SITE_ROOT=http://localhost:9080

networks:
  healthchecks:

volumes:
  static:
  caddy_data:
  db:
