version: "3.8"
# https://docs.docker.com/compose/compose-file/compose-file-v3/
services:
  caddy:
    image: caddy:latest
    # https://hub.docker.com/_/caddy
    volumes:
      - static:/var/www/healthchecks/static
      - caddy_data:/data
    networks:
      - healthchecks
      - traefik
    configs:
      - source: healthchecks_caddyfile
        target: /etc/caddy/Caddyfile
    environment:
      # https://caddyserver.com/docs/automatic-https#overview
      - DOMAIN=:80
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.healthchecks.entrypoints=websecure"
        - "traefik.http.routers.healthchecks.rule=Host(`healthchecks.yourdomain.test`)"
        - "traefik.http.services.healthchecks.loadbalancer.server.port=80" # Port traefik needs to route traffic to

  healthchecks:
    image: zeigren/healthchecks:latest # ghcr.io/zeigren/healthchecks_docker:latest
    # https://hub.docker.com/r/zeigren/healthchecks
    networks:
      - healthchecks
    volumes:
      - static:/usr/src/static
      - db:/usr/src/app/db
    environment:
      - REGISTRATION_OPEN=True
      - SITE_ROOT=https://healthchecks.yourdomain.test
      # - MATRIX_ACCESS_TOKEN=DOCKER-SECRET->BOT_MATRIX_ACCESS_TOKEN
    # secrets:
    #   - BOT_MATRIX_ACCESS_TOKEN

networks:
  healthchecks:
  traefik:
    external: true

volumes:
  static:
  caddy_data:
  db:

configs:
  healthchecks_caddyfile:
    external: true
# secrets:
#   BOT_MATRIX_ACCESS_TOKEN:
#     external: true
