version: "3.8"
# https://docs.docker.com/compose/compose-file/compose-file-v3/
services:
  nginx:
    image: nginx:alpine
    # https://hub.docker.com/_/nginx
    networks:
      - healthchecks
      - traefik
    volumes:
      - static:/var/www/healthchecks/static
    configs:
      - source: healthchecks_nginx.conf
        target: /etc/nginx/templates/nginx.conf.template
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      # https://nginx.org/en/docs/ngx_core_module.html#worker_processes
      - NGINX_WORKER_PROCESSES=auto
      # https://nginx.org/en/docs/ngx_core_module.html#worker_rlimit_nofile
      - NGINX_WORKER_RLIMIT_NOFILE=65535
      # https://nginx.org/en/docs/ngx_core_module.html#worker_connections
      - NGINX_WORKER_CONNECTIONS=65535
      # https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
      - NGINX_CLIENT_MAX_BODY_SIZE=10m
      # https://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_timeout
      - NGINX_CLIENT_BODY_TIMEOUT=30s
      - NGINX_HOST=healthchecks.yourdomain.test
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bookstack.entrypoints=websecure"
        - "traefik.http.routers.bookstack.rule=Host(`healthchecks.yourdomain.test`)"
        - "traefik.http.services.bookstack.loadbalancer.server.port=80" # Port traefik needs to route traffic to

  healthchecks:
    image: zeigren/healthchecks:latest
    # https://hub.docker.com/r/zeigren/healthchecks
    networks:
      - healthchecks
    volumes:
      - static:/usr/src/static
      - db:/usr/src/app/db
    environment:
      - REGISTRATION_OPEN=True
      - SITE_ROOT=https://healthchecks.yourdomain.test
      # - MATRIX_ACCESS_TOKEN=DOCKER-SECRET->BOT_MATRIX_ACCESS_TOKEN
    # secrets:
    #   - BOT_MATRIX_ACCESS_TOKEN

networks:
  healthchecks:
  traefik:
    external: true

volumes:
  static:
  db:

configs:
  healthchecks_nginx.conf:
    external: true
# secrets:
#   BOT_MATRIX_ACCESS_TOKEN:
#     external: true
